version: 2.1
jobs:
  lint_and_build:
    docker:
      - image: circleci/node:12.9.0
    steps:
      - checkout
      - run:
          name: Setup
          command: npm install
      - run:
          name: lint and format
          command: npm run lint
      - run:
          name: Build
          command: npm run build
  semantic_release:
    docker:
      - image: circleci/node:12.9.0
    steps:
      - checkout
      - run:
          name: Setup
          command: npm install
      - run:
          name: Release to GitHub
          command: npx semantic-release
      - run:
          name: Push Code to Bitbucket
          command: git push https://viewar_sf:${BB_APP_PW}@bitbucket.org/viewar_sf/viewar-boilerplate-react.git
      - run:
          name: Push Tags to Bitbucket
          command: git push https://viewar_sf:${BB_APP_PW}@bitbucket.org/viewar_sf/viewar-boilerplate-react.git --tags

workflows:
  version: 2
  test:
    jobs:
      - lint_and_build
      - semantic_release:
          requires:
            - lint_and_build
          filters:
            branches:
              # release per github PR
              only: master
